spring:
  application:
    name:
      BSSM_ALGORITHM
  config:
    import:
      - optional:file:env/.env[.properties]

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      okhttp:
        enabled: true
      http2client:
        enabled: true
      httpclient:
        hc5:
          enabled: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

front-url:
  - ${FRONTEND_URL_LOCAL}
  - ${FRONTEND_URL_PROD}